# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon = false

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.116.12+1.21.1
sodium_version_modrinth=mc1.21.1-0.8.12-alpha.4-fabric
sodium_extra_allows=0.8.9 0.8.10 0.8.11


# Mod Properties
mod_version = 0.2.16-beta
maven_group = me.cortex
archives_base_name = voxy